### ISSUE TITLE
Cython 3.0.0: pyroaring fails to build

### ISSUE THREAD

**Issue by penguinpee** [Ezibenroc/PyRoaringBitMap#96]
I'm attempting to package pyroaring for Fedora. The development branch and upcoing release are currently on Python3.12 and Cython 3.0.0. Using these I got the following error:

```
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
          self.__check_compatibility(other)
          cdef croaring.roaring_bitmap_t *r = func(self._c_bitmap, other._c_bitmap)
          return self.from_ptr(r)
      def __or__(self, other):
          return (<AbstractBitMap>self).binary_op(<AbstractBitMap?>other, croaring.roaring_bitmap_or)
                                                                                  ^
  ------------------------------------------------------------
  pyroaring/abstract_bitmap.pxi:447:80: Cannot assign type 'roaring_bitmap_t *(const roaring_bitmap_t *, const roaring_bitmap_t *) noexcept' to 'roaring_bitmap_t *(const roaring_bitmap_t *, const roaring_bitmap_t *) except *'
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
      def __or__(self, other):
          return (<AbstractBitMap>self).binary_op(<AbstractBitMap?>other, croaring.roaring_bitmap_or)
      def __and__(self, other):
          return (<AbstractBitMap>self).binary_op(<AbstractBitMap?>other, croaring.roaring_bitmap_and)
                                                                                  ^
  ------------------------------------------------------------
  pyroaring/abstract_bitmap.pxi:450:80: Cannot assign type 'roaring_bitmap_t *(const roaring_bitmap_t *, const roaring_bitmap_t *) noexcept' to 'roaring_bitmap_t *(const roaring_bitmap_t *, const roaring_bitmap_t *) except *'
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
      def __and__(self, other):
          return (<AbstractBitMap>self).binary_op(<AbstractBitMap?>other, croaring.roaring_bitmap_and)
      def __xor__(self, other):
          return (<AbstractBitMap>self).binary_op(<AbstractBitMap?>other, croaring.roaring_bitmap_xor)
                                                                                  ^
  ------------------------------------------------------------
  pyroaring/abstract_bitmap.pxi:453:80: Cannot assign type 'roaring_bitmap_t *(const roaring_bitmap_t *, const roaring_bitmap_t *) noexcept' to 'roaring_bitmap_t *(const roaring_bitmap_t *, const roaring_bitmap_t *) except *'
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
      def __xor__(self, other):
          return (<AbstractBitMap>self).binary_op(<AbstractBitMap?>other, croaring.roaring_bitmap_xor)
      def __sub__(self, other):
          return (<AbstractBitMap>self).binary_op(<AbstractBitMap?>other, croaring.roaring_bitmap_andnot)
                                                                                  ^
  ------------------------------------------------------------
  pyroaring/abstract_bitmap.pxi:456:80: Cannot assign type 'roaring_bitmap_t *(const roaring_bitmap_t *, const roaring_bitmap_t *) noexcept' to 'roaring_bitmap_t *(const roaring_bitmap_t *, const roaring_bitmap_t *) except *'
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
          self.__check_compatibility(other)
          func(self._c_bitmap, other._c_bitmap)
          return self
      def __ior__(self, other):
          return (<BitMap>self).binary_iop(<AbstractBitMap?>other, croaring.roaring_bitmap_or_inplace)
                                                                           ^
  ------------------------------------------------------------
  pyroaring/bitmap.pxi:115:73: Cannot assign type 'void (roaring_bitmap_t *, const roaring_bitmap_t *) noexcept' to 'void (roaring_bitmap_t *, const roaring_bitmap_t *) except *'
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
      def __ior__(self, other):
          return (<BitMap>self).binary_iop(<AbstractBitMap?>other, croaring.roaring_bitmap_or_inplace)
      def __iand__(self, other):
          return (<BitMap>self).binary_iop(<AbstractBitMap?>other, croaring.roaring_bitmap_and_inplace)
                                                                           ^
  ------------------------------------------------------------
  pyroaring/bitmap.pxi:118:73: Cannot assign type 'void (roaring_bitmap_t *, const roaring_bitmap_t *) noexcept' to 'void (roaring_bitmap_t *, const roaring_bitmap_t *) except *'
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
      def __iand__(self, other):
          return (<BitMap>self).binary_iop(<AbstractBitMap?>other, croaring.roaring_bitmap_and_inplace)
      def __ixor__(self, other):
          return (<BitMap>self).binary_iop(<AbstractBitMap?>other, croaring.roaring_bitmap_xor_inplace)
                                                                           ^
  ------------------------------------------------------------
  pyroaring/bitmap.pxi:121:73: Cannot assign type 'void (roaring_bitmap_t *, const roaring_bitmap_t *) noexcept' to 'void (roaring_bitmap_t *, const roaring_bitmap_t *) except *'
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
      def __ixor__(self, other):
          return (<BitMap>self).binary_iop(<AbstractBitMap?>other, croaring.roaring_bitmap_xor_inplace)
      def __isub__(self, other):
          return (<BitMap>self).binary_iop(<AbstractBitMap?>other, croaring.roaring_bitmap_andnot_inplace)
                                                                           ^
  ------------------------------------------------------------
  pyroaring/bitmap.pxi:124:73: Cannot assign type 'void (roaring_bitmap_t *, const roaring_bitmap_t *) noexcept' to 'void (roaring_bitmap_t *, const roaring_bitmap_t *) except *'
  Compiling pyroaring/pyroaring.pyx because it changed.
  [1/1] Cythonizing pyroaring/pyroaring.pyx
  Traceback (most recent call last):
    File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 416, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
      self.run_setup()
    File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 488, in run_setup
      self).run_setup(setup_script=setup_script)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 69, in <module>
    File "/usr/lib/python3.12/site-packages/setuptools/__init__.py", line 107, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
    File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.12/site-packages/wheel/bdist_wheel.py", line 343, in run
      self.run_command("build")
    File "/usr/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
    File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 131, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
    File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 84, in run
      _build_ext.run(self)
    File "/usr/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
      self.build_extensions()
    File "/usr/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
      self._build_extensions_serial()
    File "/usr/lib/python3.12/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
      self.build_extension(ext)
    File "/usr/lib/python3.12/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
      _build_ext.build_extension(self, ext)
    File "/usr/lib64/python3.12/site-packages/Cython/Distutils/build_ext.py", line 122, in build_extension
      new_ext = cythonize(
                ^^^^^^^^^^
    File "/usr/lib64/python3.12/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
      cythonize_one(*args)
    File "/usr/lib64/python3.12/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
      raise CompileError(None, pyx_file)
  Cython.Compiler.Errors.CompileError: pyroaring/pyroaring.pyx
  error: subprocess-exited-with-error
```

I also tried with Cython compatibility package (0.29). That gave me a different error:

```
  building 'pyroaring' extension
  creating build
  creating build/temp.linux-x86_64-cpython-312
  creating build/temp.linux-x86_64-cpython-312/pyroaring
  gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -I/usr/include/python3.12 -c pyroaring/pyroaring.cpp -o build/temp.linux-x86_64-cpython-312/pyroaring/pyroaring.o -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS "-D _GLIBCXX_ASSERTIONS" -std=c99 -O3
  gcc: fatal error: cannot execute ‘cc1plus’: execvp: No such file or directory
  compilation terminated.
  error: command '/usr/bin/gcc' failed with exit code 1
  error: subprocess-exited-with-error
```

Last but not least, in Fedora 38 (Python3.11, Cython 0.29) it builds fine.

**Comment by mbridon** [comment]
Do note that I need this to be able to build the [buildstream](https://github.com/apache/buildstream/) package which requires this, and buildstream is in turn needed for things like the freedesktop sdk for Flatpak. 😕

**Comment by penguinpee** [comment]
> I also tried with Cython compatibility package (0.29). That gave me a different error

That works now. I had to explicitly add `gcc-c++` as a build requirement. So, I guess that makes it a Cython issue rather than a Python issue. I'll update the title.

**Comment by Ezibenroc** [comment]
Hello and thank you for reporting. This should be fixed by this PR: https://github.com/Ezibenroc/PyRoaringBitMap/pull/97
If I understood well, you tried to build yourself because you use Python 3.12, right? I will see if I can add it easily in the build.

**Comment by penguinpee** [comment]
> If I understood well, you tried to build yourself because you use Python 3.12, right? I will see if I can add it easily in the build.

Yes, when packaging we build from scratch. I applied the patch from PR #97 to the GitHub sources (we were using PyPI before) and builds fine now with Cython 3.x. Thanks for the pointer.

**Comment by Ezibenroc** [comment]
I have just published release 0.4.3 on Pypi. This includes the fix from #97 (so you should be able to install from Pypi's source with Cython 3) as well as Python 3.12 wheels (so should be able to install without Cython).

**Comment by penguinpee** [comment]
We always build from source using whatever stack is currently available in the releases. Thanks for the quick release. I will update the package once release monitoring has informed me of the new version. Should be within the next 24 hours.

**Comment by Ezibenroc** [comment]
I messed up when releasing, the commit that removed the pinning of Cython version was not included (not sure what happened, it was present in the PR). I fixed this in https://github.com/Ezibenroc/PyRoaringBitMap/commit/7009ba9172b2ba39fa193f24c0f386d4ac1ac0d7 and I am releasing 0.4.4 to include this (if you install from source, version 0.4.3 will fail as before with Cython 3).

**Comment by penguinpee** [comment]
No worries. I'll wait for 0.4.4 then. Thanks for the heads up.
